* Calculators
1. Fridericia LS. Die Systolendauer im Elektrokardiogramm bei normalen Menschen und bei Herzkranken. Acta Medica Scandinavica. 1920;53(1):469-486. doi:10.1111/j.0954-6820.1920.tb18266.x
2. Cockcroft DW, Gault H. Prediction of Creatinine Clearance from Serum Creatinine. NEF. 1976;16(1):31-41. doi:10.1159/000180580
3. Hodges M, Salerno D, Erlinen D. Bazett’s QT correction reviewed: evidence that a linear QT correction for heart rate is better. J Am Coll Cardiol. 1983;1:694.
4. Sagie A, Larson MG, Goldberg RJ, Bengtson JR, Levy D. An improved method for adjusting the QT interval for heart rate (the Framingham Heart Study). American Journal of Cardiology. 1992;70(7):797-801. doi:10.1016/0002-9149(92)90562-D
5. Horton JD, Bushwick BM. Warfarin Therapy: Evolving Strategies in Anticoagulation. afp. 1999;59(3):635-646. Accessed September 3, 2022. https://www.aafp.org/pubs/afp/issues/1999/0201/p635.html
6. Rautaharju PM, Zhang ZM, Prineas R, Heiss G. Assessment of prolonged QT and JT intervals in ventricular conduction defects. American Journal of Cardiology. 2004;93(8):1017-1021. doi:10.1016/j.amjcard.2003.12.055
7. Bazett H. C. An analysis of the time‐relations of electrocardiograms. Annals of Noninvasive Electrocardiology. 2006;2(2):177-194. doi:10.1111/j.1542-474X.1997.tb00325.x
8. Levey AS, Stevens LA, Schmid CH, et al. A new equation to estimate glomerular filtration rate. Ann Intern Med. 2009;150(9):604-612. doi:10.7326/0003-4819-150-9-200905050-00006
9. Rautaharju PM, Surawicz B, Gettes LS. AHA/ACCF/HRS Recommendations for the Standardization and Interpretation of the Electrocardiogram Part IV: The ST Segment, T and U Waves, and the QT Interval: A Scientific Statement From the American Heart Association Electrocardiography and Arrhythmias Committee, Council on Clinical Cardiology; the American College of Cardiology Foundation; and the Heart Rhythm Society: Endorsed by the International Society for Computerized Electrocardiology. Circulation. 2009;119(10):e241-e250. doi:10.1161/CIRCULATIONAHA.108.191096
10. Winter MA, Guhr KN, Berg GM. Impact of various body weights and serum creatinine concentrations on the bias and accuracy of the Cockcroft-Gault equation. Pharmacotherapy. 2012;32(7):604-612. doi:10.1002/j.1875-9114.2012.01098.x
11. Yankelson L, Hochstadt A, Sadeh B, et al. New formula for defining “normal” and “prolonged” QT in patients with bundle branch block. Journal of Electrocardiology. 2018;51(3):481-486. doi:10.1016/j.jelectrocard.2017.12.039
12. Bogossian H, Linz D, Heijman J, et al. QTc evaluation in patients with bundle branch block. Int J Cardiol Heart Vasc. 2020;30:100636. doi:10.1016/j.ijcha.2020.100636
* Diagnosis
1. Lewis T. Observations upon ventricular hypertrophy with special reference to preponderance of one or the other chamber. Heart. 1914;5:367-402.
2. Myers GB, Klein HA, Stofer BE. The electrocardiographic diagnosis of right ventricular hypertrophy. Am Heart J. 1948;35(1):1-40. doi:10.1016/0002-8703(48)90182-3
3. Sokolow M, Lyon TP. The ventricular complex in left ventricular hypertrophy as obtained by unipolar precordial and limb leads. Am Heart J. 1949;37(2):161-186. doi:10.1016/0002-8703(49)90562-1
4. Romhilt DW, Estes EH. A point-score system for the ECG diagnosis of left ventricular hypertrophy. Am Heart J. 1968;75(6):752-758. doi:10.1016/0002-8703(68)90035-5
5. Wellens HJ, Bär FW, Lie KI. The value of the electrocardiogram in the differential diagnosis of a tachycardia with a widened QRS complex. Am J Med. 1978;64(1):27-33. doi:10.1016/0002-9343(78)90176-6
6. Butler PM, Leggett SI, Howe CM, Freye CJ, Hindman NB, Wagner GS. Identification of electrocardiographic criteria for diagnosis of right ventricular hypertrophy due to mitral stenosis. Am J Cardiol. 1986;57(8):639-643. doi:10.1016/0002-9149(86)90850-7
7. Milstein S, Sharma AD, Guiraudon GM, Klein GJ. An algorithm for the electrocardiographic localization of accessory pathways in the Wolff-Parkinson-White syndrome. Pacing Clin Electrophysiol. 1987;10(3 Pt 1):555-563. doi:10.1111/j.1540-8159.1987.tb04520.x
8. Brugada P, Brugada J, Mont L, Smeets J, Andries EW. A new approach to the differential diagnosis of a regular tachycardia with a wide QRS complex. Circulation. 1991;83(5):1649-1659. doi:10.1161/01.cir.83.5.1649
9. McKenna WJ, Thiene G, Nava A, et al. Diagnosis of arrhythmogenic right ventricular dysplasia/cardiomyopathy. Task Force of the Working Group Myocardial and Pericardial Disease of the European Society of Cardiology and of the Scientific Council on Cardiomyopathies of the International Society and Federation of Cardiology. Br Heart J. 1994;71(3):215-218. Accessed September 4, 2022. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC483655/
10. d’Avila A, Brugada J, Skeberis V, Andries E, Sosa E, Brugada P. A fast and reliable algorithm to localize accessory pathways based on the polarity of the QRS complex on the surface ECG during sinus rhythm. Pacing Clin Electrophysiol. 1995;18(9 Pt 1):1615-1627. doi:10.1111/j.1540-8159.1995.tb06983.x
11. Wilber DJ, Kopp DE, Glascock DO DN, Kinder CA, Kall JG. Catheter Ablation of the Mitral Isthmus for Ventricular Tachycardia Associated With Inferior Infarction. Circulation. 1995;92(12):3481-3489. doi:10.1161/01.CIR.92.12.3481
12. Arruda MS, McClelland JH, Wang X, et al. Development and validation of an ECG algorithm for identifying accessory pathway ablation site in Wolff-Parkinson-White syndrome. J Cardiovasc Electrophysiol. 1998;9(1):2-12. doi:10.1111/j.1540-8167.1998.tb00861.x
13. Wilde AAM, Antzelevitch C, Borggrefe M, et al. Proposed Diagnostic Criteria for the Brugada Syndrome. Circulation. 2002;106(19):2514-2519. doi:10.1161/01.CIR.0000034169.45752.4A
14. Berruezo A, Mont L, Nava S, Chueca E, Bartholomay E, Brugada J. Electrocardiographic Recognition of the Epicardial Origin of Ventricular Tachycardias. Circulation. 2004;109(15):1842-1847. doi:10.1161/01.CIR.0000125525.04081.4B
15. Hsieh BP, Pham MX, Froelicher VF. Prognostic value of electrocardiographic criteria for left ventricular hypertrophy. American Heart Journal. 2005;150(1):161-167. doi:10.1016/j.ahj.2004.08.041
16. Joshi S, Wilber DJ. Ablation of idiopathic right ventricular outflow tract tachycardia: current perspectives. J Cardiovasc Electrophysiol. 2005;16 Suppl 1:S52-58. doi:10.1111/j.1540-8167.2005.50163.x
17. Srivathsan K, Lester SJ, Appleton CP, Scott LR, Munger TM. Ventricular Tachycardia in the Absence of Structural Heart Disease. Indian Pacing Electrophysiol J. 2005;5(2):106-121. Accessed September 8, 2022. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1502082/
18. Tada H, Ito S, Naito S, et al. Idiopathic ventricular arrhythmia arising from the mitral annulus: a distinct subgroup of idiopathic ventricular arrhythmias. J Am Coll Cardiol. 2005;45(6):877-886. doi:10.1016/j.jacc.2004.12.025
19. Tanner H, Hindricks G, Schirdewahn P, et al. Outflow tract tachycardia with R/S transition in lead V3. Journal of the American College of Cardiology. 2005;45(3):418-423. doi:10.1016/j.jacc.2004.10.037
20. Kistler PM, Roberts -Thomson Kurt C., Haqqani HM, et al. P-Wave Morphology in Focal Atrial Tachycardia. Journal of the American College of Cardiology. 2006;48(5):1010-1017. doi:10.1016/j.jacc.2006.03.058
21. Szilágyi SM, Szilágyi L, Görög LK, et al. An Enhanced Accessory Pathway Localization Method for Efficient Treatment of Wolff-Parkinson-White Syndrome. In: Ruiz-Shulcloper J, Kropatsch WG, eds. Progress in Pattern Recognition, Image Analysis and Applications. Vol 5197. Lecture Notes in Computer Science. Springer Berlin Heidelberg; 2008:269-276. doi:10.1007/978-3-540-85920-8_33
22. Vereckei A, Duray G, Szénási G, Altemose GT, Miller JM. New algorithm using only lead aVR for differential diagnosis of wide QRS complex tachycardia. Heart Rhythm. 2008;5(1):89-98. doi:10.1016/j.hrthm.2007.09.020
23. Hancock EW, Deal BJ, Mirvis DM, Okin P, Kligfield P, Gettes LS. AHA/ACCF/HRS Recommendations for the Standardization and Interpretation of the Electrocardiogram. Journal of the American College of Cardiology. 2009;53(11):992-1002. doi:10.1016/j.jacc.2008.12.015
24. Marcus FI, McKenna WJ, Sherrill D, et al. Diagnosis of arrhythmogenic right ventricular cardiomyopathy/dysplasia: Proposed Modification of the Task Force Criteria. European Heart Journal. 2010;31(7):806-814. doi:10.1093/eurheartj/ehq025
25. Pava LF, Perafán P, Badiel M, et al. R-wave peak time at DII: a new criterion for differentiating between wide complex QRS tachycardias. Heart Rhythm. 2010;7(7):922-926. doi:10.1016/j.hrthm.2010.03.001
26. Betensky BP, Park RE, Marchlinski FE, et al. The V(2) transition ratio: a new electrocardiographic criterion for distinguishing left from right ventricular outflow tract tachycardia origin. J Am Coll Cardiol. 2011;57(22):2255-2262. doi:10.1016/j.jacc.2011.01.035
27. Gollob MH, Redpath CJ, Roberts JD. The short QT syndrome: proposed diagnostic criteria. J Am Coll Cardiol. 2011;57(7):802-812. doi:10.1016/j.jacc.2010.09.048
28. Schwartz PJ, Crotti L. QTc behavior during exercise and genetic testing for the long-QT syndrome. Circulation. 2011;124(20):2181-2184. doi:10.1161/CIRCULATIONAHA.111.062182
29. Strauss DG, Selvester RH, Wagner GS. Defining Left Bundle Branch Block in the Era of Cardiac Resynchronization Therapy. American Journal of Cardiology. 2011;107(6):927-934. doi:10.1016/j.amjcard.2010.11.010
30. Priori SG, Wilde AA, Horie M, et al. HRS/EHRA/APHRS Expert Consensus Statement on the Diagnosis and Management of Patients with Inherited Primary Arrhythmia Syndromes: Document endorsed by HRS, EHRA, and APHRS in May 2013 and by ACCF, AHA, PACES, and AEPC in June 2013. Heart Rhythm. 2013;10(12):1932-1963. doi:10.1016/j.hrthm.2013.05.014
31. Ristić AD, Imazio M, Adler Y, et al. Triage strategy for urgent management of cardiac tamponade: a position statement of the European Society of Cardiology Working Group on Myocardial and Pericardial Diseases. European Heart Journal. 2014;35(34):2279-2284. doi:10.1093/eurheartj/ehu217
32. Antzelevitch C, Yan GX, Ackerman MJ, et al. J-Wave syndromes expert consensus conference report: Emerging concepts and gaps in knowledge. J Arrhythm. 2016;32(5):315-339. doi:10.1016/j.joa.2016.07.002
33. Adler A, Novelli V, Amin AS, et al. An International, Multicentered, Evidence-Based Reappraisal of Genes Reported to Cause Congenital Long QT Syndrome. Circulation. 2020;141(6):418-428. doi:10.1161/CIRCULATIONAHA.119.043132
* Reference and Tools
1. Martínez-Alday JD, Almendral J, Arenal A, et al. Identification of concealed posteroseptal Kent pathways by comparison of ventriculoatrial intervals from apical and posterobasal right ventricular sites. Circulation. 1994;89(3):1060-1067. doi:10.1161/01.cir.89.3.1060
2. Hirao K, Otomo K, Wang X, et al. Para-Hisian pacing. A new method for differentiating retrograde conduction over an accessory AV pathway from conduction over the AV node. Circulation. 1996;94(5):1027-1035. doi:10.1161/01.cir.94.5.1027
3. Stevenson WG, Friedman PL, Sager PT, et al. Exploring Postinfarction Reentrant Ventricular Tachycardia With Entrainment Mapping. Journal of the American College of Cardiology. 1997;29(6):1180-1189. doi:10.1016/S0735-1097(97)00065-X
4. El-Shalakany A, Hadjis T, Papageorgiou P, Monahan K, Epstein L, Josephson ME. Entrainment/Mapping Criteria for the Prediction of Termination of Ventricular Tachycardia by Single Radiofrequency Lesion in Patients With Coronary Artery Disease. Circulation. 1999;99(17):2283-2289. doi:10.1161/01.CIR.99.17.2283
5. M. D. Josephson ME. Clinical Cardiac Electrophysiology: Techniques and Interpretations. 4th edition. Lippincott Williams & Wilkins; 2008. https://www.amazon.com/Clinical-Cardiac-Electrophysiology-Techniques-Interpretations/dp/0781777399
6. CMS. Decision Memo for Implantable Cardioverter Defibrillators (CAG-00157R4) Feb 15, 2018. Published online February 15, 2018. https://www.cms.gov/medicare-coverage-database/view/ncacal-decision-memo.aspx?proposed=N&NCAId=288
* Risk Scores
1. Martin TP, Hanusa BH, Kapoor WN. Risk stratification of patients with syncope. Ann Emerg Med. 1997;29(4):459-466. doi:10.1016/s0196-0644(97)70217-8
2. Gage BF, Waterman AD, Shannon W, Boechler M, Rich MW, Radford MJ. Validation of Clinical Classification Schemes for Predicting StrokeResults From the National Registry of Atrial Fibrillation. JAMA. 2001;285(22):2864-2870. doi:10.1001/jama.285.22.2864
3. McKenna WJ. Hypertrophic cardiomyopathy: management, risk stratification, and prevention of sudden death. Heart. 2002;87(2):169-176. doi:10.1136/heart.87.2.169
4. Colivicchi F, Ammirati F, Melina D, et al. Development and prospective validation of a risk stratification system for patients with syncope in the emergency department: the OESIL risk score. Eur Heart J. 2003;24(9):811-819. doi:10.1016/s0195-668x(02)00827-8
5. Gage BF, Yan Y, Milligan PE, et al. Clinical classification schemes for predicting hemorrhage: results from the National Registry of Atrial Fibrillation (NRAF). Am Heart J. 2006;151(3):713-719. doi:10.1016/j.ahj.2005.04.017
6. Quinn J, McDermott D, Stiell I, Kohn M, Wells G. Prospective validation of the San Francisco Syncope Rule to predict patients with serious outcomes. Ann Emerg Med. 2006;47(5):448-454. doi:10.1016/j.annemergmed.2005.11.019
7. Del Rosso A, Ungar A, Maggi R, et al. Clinical predictors of cardiac syncope at initial evaluation in patients referred urgently to a general hospital: the EGSYS score. Heart. 2008;94(12):1620-1626. doi:10.1136/hrt.2008.143123
8. Goldenberg I, Vyas AK, Hall WJ, et al. Risk Stratification for Primary Implantation of a Cardioverter-Defibrillator in Patients With Ischemic Left Ventricular Dysfunction. Journal of the American College of Cardiology. 2008;51(3):288-296. doi:10.1016/j.jacc.2007.08.058
9. Lip GYH, Nieuwlaat R, Pisters R, Lane DA, Crijns HJGM. Refining clinical risk stratification for predicting stroke and thromboembolism in atrial fibrillation using a novel risk factor-based approach: the euro heart survey on atrial fibrillation. Chest. 2010;137(2):263-272. doi:10.1378/chest.09-1584
10. Pisters R, Lane DA, Nieuwlaat R, de Vos CB, Crijns HJGM, Lip GYH. A novel user-friendly score (HAS-BLED) to assess 1-year risk of major bleeding in patients with atrial fibrillation: the Euro Heart Survey. Chest. 2010;138(5):1093-1100. doi:10.1378/chest.10-0134
11. Fang MC, Go AS, Chang Y, et al. A New Risk Scheme to Predict Warfarin-Associated Hemorrhage. Journal of the American College of Cardiology. 2011;58(4):395-401. doi:10.1016/j.jacc.2011.03.031
12. Friberg L, Rosenqvist M, Lip G. Evaluation of risk stratification schemes for ischaemic stroke and bleeding in 182 678 patients with atrial fibrillation: The Swedish Atrial Fibrillation Cohort Study. European heart journal. 2012;33:1500-1510. doi:10.1093/eurheartj/ehr488
13. Apostolakis S, Sullivan RM, Olshansky B, Lip GYH. Factors affecting quality of anticoagulation control among patients with atrial fibrillation on warfarin: the SAMe-TT₂R₂ score. Chest. 2013;144(5):1555-1563. doi:10.1378/chest.13-0054
14. Singer DE, Chang Y, Borowsky LH, et al. A new risk scheme to predict ischemic stroke and other thromboembolism in atrial fibrillation: the ATRIA study stroke risk score. J Am Heart Assoc. 2013;2(3):e000250. doi:10.1161/JAHA.113.000250
15. Tisdale JE, Jaynes HA, Kingery JR, et al. Development and Validation of a Risk Score to Predict QT Interval Prolongation in Hospitalized Patients. Circulation: Cardiovascular Quality and Outcomes. 2013;6(4):479-487. doi:10.1161/CIRCOUTCOMES.113.000152
16. Dodson JA, Reynolds MR, Bao H, et al. Developing a Risk Model for In-Hospital Adverse Events Following Implantable Cardioverter-Defibrillator Implantation. Journal of the American College of Cardiology. 2014;63(8):788-796. doi:10.1016/j.jacc.2013.09.079
17. O’Mahony C, Jichi F, Pavlou M, et al. A novel clinical risk prediction model for sudden cardiac death in hypertrophic cardiomyopathy (HCM Risk-SCD). European Heart Journal. 2014;35(30):2010-2020. doi:10.1093/eurheartj/eht439
18. 2014 ESC Guidelines on diagnosis and management of hypertrophic cardiomyopathy: The Task Force for the Diagnosis and Management of Hypertrophic Cardiomyopathy of the European Society of Cardiology (ESC). Eur Heart J. 2014;35(39):2733-2779. doi:10.1093/eurheartj/ehu284
19. Kornej J, Hindricks G, Shoemaker MB, et al. The APPLE score: a novel and simple score for the prediction of rhythm outcomes after catheter ablation of atrial fibrillation. Clin Res Cardiol. 2015;104(10):871-876. doi:10.1007/s00392-015-0856-x
20. O’Brien EC, Simon DN, Thomas LE, et al. The ORBIT bleeding score: a simple bedside score to assess bleeding risk in atrial fibrillation. Eur Heart J. 2015;36(46):3258-3264. doi:10.1093/eurheartj/ehv476
21. Kornej J, Hindricks G, Arya A, Sommer P, Husser D, Bollmann A. The APPLE Score – A Novel Score for the Prediction of Rhythm Outcomes after Repeat Catheter Ablation of Atrial Fibrillation. PLoS One. 2017;12(1):e0169933. doi:10.1371/journal.pone.0169933
22. Cadrin-Tourigny J, Bosman LP, Nozza A, et al. Retracted and Republished: A new prediction model for ventricular arrhythmias in arrhythmogenic right ventricular cardiomyopathy. European Heart Journal. 2019;40(23):1850-1858. doi:10.1093/eurheartj/ehz103
23. Cadrin-Tourigny J, Bosman LP, Wang W, et al. Sudden Cardiac Death Prediction in Arrhythmogenic Right Ventricular Cardiomyopathy: A Multinational Collaboration. Circ: Arrhythmia and Electrophysiology. 2021;14(1):e008509. doi:10.1161/CIRCEP.120.008509
24. Cadrin-Tourigny J, Bosman LP, Nozza A, et al. A new prediction model for ventricular arrhythmias in arrhythmogenic right ventricular cardiomyopathy. European Heart Journal. Published online April 20, 2022:ehac180. doi:10.1093/eurheartj/ehac180
25. Steverink N, Slaets, Schuurmans H, Lis  van. Measuring frailty. The Gerontologist. 2001;41:236-237.
26. Schuurmans H, Steverink N, Lindenberg S, Frieswijk N, Slaets JPJ. Old or Frail: What Tells Us More? The Journals of Gerontology Series A: Biological Sciences and Medical Sciences. 2004;59(9):M962-M965. doi:10.1093/gerona/59.9.M962
27. Drubbel I, Bleijenberg N, Kranenburg G, et al. Identifying frailty: do the Frailty Index and Groningen Frailty Indicator cover different clinical perspectives? a cross-sectional study. BMC Fam Pract. 2013;14:64. doi:10.1186/1471-2296-14-64
